### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by Scipio1996** [mshukor/eP-ALM#1]
Hi:

Great work, but I found it seems missing all running codes, such as vqa.py, video_vqa.py and so on.

Can you add them?

Thank you very much,

**Comment by mshukor** [comment]
Hi, the training code with accelerate  can be found in the [accelerate_training](https://github.com/mshukor/eP-ALM/tree/main/accelerate_training) folder, and those with float32 in [float32](https://github.com/mshukor/eP-ALM/tree/main/float32).

**Comment by Scipio1996** [comment]
Thank you for your quick response, I have found it.
 Maybe you can revise the code in shell, eg. in [ePALM_caption.sh](https://github.com/mshukor/eP-ALM/blob/main/run_scripts/float32/image/ePALM_caption.sh), change "caption.py" to "float32/caption.py". So it will be ok.
