### ISSUE TITLE
How to change the decoding method to greedy decoding?

### ISSUE THREAD

**Issue by Rainlt** [mshukor/eP-ALM#2]
Nice work! I'm very interested in your work, but I‘m a bit confused.

I have tried to run the scripts "run_scripts/float32/video/ePALM_video_qa_msvd.sh" to train the model, but I can only get the test acc 0.316, which is similay to the acc reported with Multinomial decoding. Maybe the code is still using Multinomial decoding, so how can I change it to greedy decoding?

By the way, I have changed the number of "nproc_per_node" to 1, and "batch_size_train" to 32, for I have only one GPU. Is there any error?

**Comment by mshukor** [comment]
Hello,
in the config file there is two parameters (num_beams and do_sample)

For greedy:  `num_beams: 1` and `do_sample: True`
For greedy beam search=3: `num_beams: 3` and `do_sample: False`

Make sure this is still the case when doing the evaluation (like printing these parameters)

**Comment by Rainlt** [comment]
> Hello, in the config file there is two parameters (num_beams and do_sample)
> 
> For greedy: `num_beams: 1` and `do_sample: True` For greedy beam search=3: `num_beams: 3` and `do_sample: False`
> 
> Make sure this is still the case when doing the evaluation (like printing these parameters)

ok I got it. Thanks for your reply!
