### ISSUE TITLE
Missing data json file

### ISSUE THREAD

**Issue by bellos1203** [mshukor/eP-ALM#3]
Hello :)

Thank you for your great work, but I found the repo does not have some data json files in the provided link.
To be specific, `valid.json` file for GQA task. And may be more.
Moreover, `train.json` file for GQA seems broke, since the last line of given file is not ended with the bracket "}"

Could you please check and add them?

Thank you for your consideration in advance :)

**Comment by mshukor** [comment]
Hey,

I uploaded the valid.json and the correct train.json,
If there is anything else missing let me know,

Thanks

**Comment by bellos1203** [comment]
Thanks for your consideration. :) I've checked them.
